networks:
  frontend:
    # Add 'external: true' to use an existing network
    # Añade 'external: true' para usar una red existente
    #external: true
  backend:
    #external: true

services:
  db:
    image: mariadb:latest
    container_name: pureftpd-db
    restart: always
    volumes:
      - /root/s-ftp/db:/var/lib/mysql
      - /root/s-ftp/users.sql:/docker-entrypoint-initdb.d/users.sql
    environment:
      TZ: Europe/Madrid
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: pureftpd
      MYSQL_USER: $[USER]
      MYSQL_PASSWORD: $[PASS]
    networks:
      - backend

  pureftpd:
    image: crazymax/pure-ftpd
    container_name: pureftpd
    restart: always
    depends_on:
      - db
    volumes:
      - /root/s-ftp/data/:/data/
      - /root/s-ftp/$[USER]:/home/$[USER]/
    environment:
      TZ: Europe/Madrid
      AUTH_METHOD: mysql
    networks:
      - frontend
      - backend
    ports:
      - "2100:2100"
      - "30000-30009:30000-30009"
