networks:
  frontend:
    # Add 'external: true' to use an existing network
    # Añade 'external: true' para usar una red existente
    external: true
  backend:
    external: true

services:
  db:
    image: mariadb:latest
    container_name: pureftpd-db
    restart: always
    volumes:
      - ./db:/var/lib/mysql
      - ./users.sql:/docker-entrypoint-initdb.d/users.sql
    environment:
      TZ: Europe/Madrid
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: pureftpd
      MYSQL_USER: bob
      MYSQL_PASSWORD: t4hmPb9wMsGrY4
    networks:
      - backend

  pureftpd1:
    image: crazymax/pure-ftpd
    container_name: pureftpd1
    restart: always
    depends_on:
      - db
    volumes:
      - ./data/:/data/
      - ./foo:/home/foo/
      - ./bob:/home/bob/
    environment:
      TZ: Europe/Madrid
      AUTH_METHOD: mysql
    networks:
      - frontend
      - backend
    ports:
      - "2100:2100"
      - "30000-30009:30000-30009"

#  pureftpd2:
#    image: crazymax/pure-ftpd
#    container_name: pureftpd2
#    restart: always
#    depends_on:
#      - db
#    volumes:
#      - ./data/ftp2:/data
#    environment:
#      TZ: Europe/Madrid
#      AUTH_METHOD: mysql
#    networks:
#      - frontend
#      - backend
#    ports:
#      - "1200:21"
#      - "30010-30019:30010-30019"